version: 0.1
phases:
    install:
        commands:
            - npm install
            - npm install -g serverless
    build:
        commands:
            - serverless deploy | tee deploy.out
    post_build:
        commands:
            - echo "Service Deployed"
